version: '3.4'

networks:
  backend:
  frontend:

services:
  vegefoodsdb:
    container_name: vegefoodsdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=1qazZAQ!
    networks:
        - backend
    ports:
        - 8001:1433
  vegefoods.api:
    container_name: vegefoods-api
    image: vominhman/vegefoodsapi
    networks:
       - backend
    ports:
        - 5296:8080
    depends_on:
        - vegefoodsdb
    environment:
        - DB_HOST=vegefoodsdb
        - DB_NAME=vegefoods
        - DB_SA_PASSWORD=1qazZAQ!
  reactui:
    container_name: react-web-ui
    image: vominhman/vegefoods.reactui    
    ports:
      - 3000:80
    networks:
      - frontend
  angularui:
    container_name: angular-web-ui
    image: vominhman/vegefoods.angularui
    ports:
      - 4200:80
    networks:
      - frontend
